definitions:
  steps:
    - step: &deploy
        name: Deploy to Hetzner Server
        image: node:22-slim
        oidc: false
        script:

          - '[[ $BITBUCKET_BRANCH = "main" ]] && DEPLOYMENT_NAME="production" || DEPLOYMENT_NAME="staging"'
          - echo $DEPLOYMENT_NAME
          - echo ${DEPLOY_PATH}
          - echo $BITBUCKET_CLONE_DIR

          # rsync
          - pipe: atlassian/rsync-deploy:0.13.0
            variables:
              USER: $SSH_USER
              SERVER: $SERVER_HOST
              SSH_KEY: $SSH_PRIVATE_KEY
              REMOTE_PATH: ${DEPLOY_PATH}
              LOCAL_PATH: $BITBUCKET_CLONE_DIR/build
              DEBUG: 'true'
              EXTRA_ARGS: 
                - "--exclude-from=.deployignore"
                - "--verbose"
          
          # ssh
          - pipe: atlassian/ssh-run:0.8.1
            variables:
              SSH_USER: $SSH_USER
              SERVER: $SERVER_HOST
              SSH_KEY: $SSH_PRIVATE_KEY
              COMMAND: |
                cat > ${DEPLOY_PATH}/.env << 'EOF'
                # Database Configuration
                DB_HOST=${DB_HOST}
                DB_PORT=${DB_PORT}
                DB_USERNAME=${DB_USERNAME}
                DB_PASSWORD="${DB_PASSWORD}"
                DB_NAME=${DB_NAME}
                
                # Application Configuration
                NODE_ENV=${NODE_ENV}
                EOF
                
                cd ${DEPLOY_PATH}
                npm ci
                npm run build
                npm run migration:run
                npm run pm2:restart || npm run pm2:start
                pm2 status

pipelines:
  branches:
    #main:
      #- step: *deploy
    staging:
      - stage:
          name: Deploy to staging
          deployment: staging
          steps:
            - step: *deploy